In [2]:
# imports
import polars as pl
from pathlib import Path

In [14]:
FILE = Path('datasets/dataframe_final.pq')

In [15]:
df = pl.read_parquet(FILE)

In [17]:
COLUMNS = [
    'order_status',
    'order_approved_at',
    'review_score',
    'payment_value_sum',
    'count_payment_installments',
    'customer_state',
    'product_category_name',
    'product_photos_qty',
    'seller_state'
]

In [18]:
df = df.select(COLUMNS)

In [19]:
print(df)

shape: (99_441, 9)
┌──────────────┬──────────────┬──────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ order_status ┆ order_approv ┆ review_score ┆ payment_val ┆ … ┆ customer_st ┆ product_cat ┆ product_pho ┆ seller_stat │
│ ---          ┆ ed_at        ┆ ---          ┆ ue_sum      ┆   ┆ ate         ┆ egory_name  ┆ tos_qty     ┆ e           │
│ str          ┆ ---          ┆ i64          ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ str          ┆              ┆ f64         ┆   ┆ str         ┆ str         ┆ i64         ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ delivered    ┆ 2017-10-02   ┆ 4            ┆ 38.71       ┆ … ┆ SP          ┆ utilidades_ ┆ 4           ┆ SP          │
│              ┆ 11:07:15     ┆              ┆             ┆   ┆             ┆ domesticas  ┆             ┆             │
│ delivered    ┆ 2018-07-26   ┆ 4            ┆ 141.46      ┆ … ┆ BA          ┆ perfumaria  ┆ 1           ┆ SP          │
│              ┆ 03:24:27     ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ delivered    ┆ 2018-08-08   ┆ null         ┆ 179.12      ┆ … ┆ GO          ┆ automotivo  ┆ 1           ┆ SP          │
│              ┆ 08:55:23     ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ delivered    ┆ 2017-11-18   ┆ 5            ┆ 72.2        ┆ … ┆ RN          ┆ pet_shop    ┆ 3           ┆ MG          │
│              ┆ 19:45:59     ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ delivered    ┆ 2018-02-13   ┆ null         ┆ 28.62       ┆ … ┆ SP          ┆ papelaria   ┆ 4           ┆ SP          │
│              ┆ 22:20:29     ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ …            ┆ …            ┆ …            ┆ …           ┆ … ┆ …           ┆ …           ┆ …           ┆ …           │
│ delivered    ┆ 2017-03-09   ┆ null         ┆ 85.08       ┆ … ┆ SP          ┆ beleza_saud ┆ 1           ┆ SP          │
│              ┆ 09:54:05     ┆              ┆             ┆   ┆             ┆ e           ┆             ┆             │
│ delivered    ┆ 2018-02-06   ┆ 4            ┆ 195.0       ┆ … ┆ SP          ┆ bebes       ┆ 4           ┆ SP          │
│              ┆ 13:10:37     ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ delivered    ┆ 2017-08-27   ┆ 5            ┆ 271.01      ┆ … ┆ BA          ┆ eletrodomes ┆ 2           ┆ SP          │
│              ┆ 15:04:16     ┆              ┆             ┆   ┆             ┆ ticos_2     ┆             ┆             │
│ delivered    ┆ 2018-01-08   ┆ 2            ┆ 441.16      ┆ … ┆ RJ          ┆ informatica ┆ 1           ┆ MG          │
│              ┆ 21:36:21     ┆              ┆             ┆   ┆             ┆ _acessorios ┆             ┆             │
│ delivered    ┆ 2018-03-09   ┆ null         ┆ 86.86       ┆ … ┆ PR          ┆ beleza_saud ┆ 1           ┆ SP          │
│              ┆ 11:20:28     ┆              ┆             ┆   ┆             ┆ e           ┆             ┆             │
└──────────────┴──────────────┴──────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [23]:
# adjust data
df = df.with_columns(
    pl.col('order_approved_at')
      .str.to_datetime(format='%Y-%m-%d %H:%M:%S')
      .dt.date()
      .alias('order_approved_at')
)

In [24]:
df

shape: (99_441, 9)
┌──────────────┬──────────────┬──────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ order_status ┆ order_approv ┆ review_score ┆ payment_val ┆ … ┆ customer_st ┆ product_cat ┆ product_pho ┆ seller_stat │
│ ---          ┆ ed_at        ┆ ---          ┆ ue_sum      ┆   ┆ ate         ┆ egory_name  ┆ tos_qty     ┆ e           │
│ str          ┆ ---          ┆ i64          ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ date         ┆              ┆ f64         ┆   ┆ str         ┆ str         ┆ i64         ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ delivered    ┆ 2017-10-02   ┆ 4            ┆ 38.71       ┆ … ┆ SP          ┆ utilidades_ ┆ 4           ┆ SP          │
│              ┆              ┆              ┆             ┆   ┆             ┆ domesticas  ┆             ┆             │
│ delivered    ┆ 2018-07-26   ┆ 4            ┆ 141.46      ┆ … ┆ BA          ┆ perfumaria  ┆ 1           ┆ SP          │
│ delivered    ┆ 2018-08-08   ┆ null         ┆ 179.12      ┆ … ┆ GO          ┆ automotivo  ┆ 1           ┆ SP          │
│ delivered    ┆ 2017-11-18   ┆ 5            ┆ 72.2        ┆ … ┆ RN          ┆ pet_shop    ┆ 3           ┆ MG          │
│ delivered    ┆ 2018-02-13   ┆ null         ┆ 28.62       ┆ … ┆ SP          ┆ papelaria   ┆ 4           ┆ SP          │
│ …            ┆ …            ┆ …            ┆ …           ┆ … ┆ …           ┆ …           ┆ …           ┆ …           │
│ delivered    ┆ 2017-03-09   ┆ null         ┆ 85.08       ┆ … ┆ SP          ┆ beleza_saud ┆ 1           ┆ SP          │
│              ┆              ┆              ┆             ┆   ┆             ┆ e           ┆             ┆             │
│ delivered    ┆ 2018-02-06   ┆ 4            ┆ 195.0       ┆ … ┆ SP          ┆ bebes       ┆ 4           ┆ SP          │
│ delivered    ┆ 2017-08-27   ┆ 5            ┆ 271.01      ┆ … ┆ BA          ┆ eletrodomes ┆ 2           ┆ SP          │
│              ┆              ┆              ┆             ┆   ┆             ┆ ticos_2     ┆             ┆             │
│ delivered    ┆ 2018-01-08   ┆ 2            ┆ 441.16      ┆ … ┆ RJ          ┆ informatica ┆ 1           ┆ MG          │
│              ┆              ┆              ┆             ┆   ┆             ┆ _acessorios ┆             ┆             │
│ delivered    ┆ 2018-03-09   ┆ null         ┆ 86.86       ┆ … ┆ PR          ┆ beleza_saud ┆ 1           ┆ SP          │
│              ┆              ┆              ┆             ┆   ┆             ┆ e           ┆             ┆             │
└──────────────┴──────────────┴──────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [42]:
GRUPED_COLS = [
    'order_status',
    'order_approved_at',
    'review_score',
    'count_payment_installments',
    'customer_state',
    'product_category_name',
    'product_photos_qty',
    'seller_state'
]
df_grouped = df.group_by(GRUPED_COLS).agg(
    pl.col('payment_value_sum').mean().alias('total_value'),
    pl.len().alias('count')
)

In [43]:
df_grouped

shape: (95_458, 10)
┌──────────────┬───────────────┬──────────────┬───────────────┬───┬───────────────┬──────────────┬─────────────┬───────┐
│ order_status ┆ order_approve ┆ review_score ┆ count_payment ┆ … ┆ product_photo ┆ seller_state ┆ total_value ┆ count │
│ ---          ┆ d_at          ┆ ---          ┆ _installments ┆   ┆ s_qty         ┆ ---          ┆ ---         ┆ ---   │
│ str          ┆ ---           ┆ i64          ┆ ---           ┆   ┆ ---           ┆ str          ┆ f64         ┆ u32   │
│              ┆ date          ┆              ┆ i64           ┆   ┆ i64           ┆              ┆             ┆       │
╞══════════════╪═══════════════╪══════════════╪═══════════════╪═══╪═══════════════╪══════════════╪═════════════╪═══════╡
│ delivered    ┆ 2017-03-07    ┆ null         ┆ 1             ┆ … ┆ 1             ┆ PR           ┆ 42.42       ┆ 1     │
│ delivered    ┆ 2017-07-08    ┆ null         ┆ 1             ┆ … ┆ 1             ┆ SP           ┆ 30.49       ┆ 1     │
│ delivered    ┆ 2018-06-29    ┆ null         ┆ 2             ┆ … ┆ 6             ┆ SC           ┆ 81.34       ┆ 1     │
│ delivered    ┆ 2018-03-23    ┆ 1            ┆ 3             ┆ … ┆ 1             ┆ SP           ┆ 193.22      ┆ 1     │
│ delivered    ┆ 2017-12-07    ┆ null         ┆ 1             ┆ … ┆ 1             ┆ SP           ┆ 126.5       ┆ 2     │
│ …            ┆ …             ┆ …            ┆ …             ┆ … ┆ …             ┆ …            ┆ …           ┆ …     │
│ delivered    ┆ 2017-11-25    ┆ 5            ┆ 10            ┆ … ┆ 1             ┆ SP           ┆ 117.85      ┆ 1     │
│ delivered    ┆ 2017-04-28    ┆ null         ┆ 3             ┆ … ┆ 2             ┆ SP           ┆ 34.78       ┆ 1     │
│ delivered    ┆ 2017-11-07    ┆ null         ┆ 10            ┆ … ┆ 1             ┆ PR           ┆ 104.26      ┆ 1     │
│ delivered    ┆ 2017-04-01    ┆ null         ┆ 4             ┆ … ┆ null          ┆ SP           ┆ 204.08      ┆ 1     │
│ delivered    ┆ 2017-03-13    ┆ null         ┆ 1             ┆ … ┆ 1             ┆ MG           ┆ 48.06       ┆ 1     │
└──────────────┴───────────────┴──────────────┴───────────────┴───┴───────────────┴──────────────┴─────────────┴───────┘

In [45]:
df_grouped.write_excel('cubes/00_cubo.xlsx')

Com esse cubo e usando `pivot_tables` do `Excel` é possivel chegar nas visualizações desejadas.