In [1]:
import pandas as pd

# O que é uma `Series`

# Por que uma `Series` possui `index`

# Qual a relação entre uma `Series` e um `DataFrame`

# Quando usar uma `list`, `np.array` ou `Series`

In [18]:
data_series

0    7.5
1    8.0
2    6.2
3    9.3
4    5.8
5    4.7
6    8.9
7    7.1
8    6.5
9    9.8
dtype: float64

In [2]:
data = [7.5, 8.0, 6.2, 9.3, 5.8, 4.7, 8.9, 7.1, 6.5, 9.8]

In [25]:
data_series = pd.Series(data, name='notas')
data_seriesA = pd.Series(data, name='notasA')

In [6]:
data_series.mean()

np.float64(7.38)

In [7]:
data_series.describe()

count    10.00000
mean      7.38000
std       1.63897
min       4.70000
25%       6.27500
50%       7.30000
75%       8.67500
max       9.80000
dtype: float64

In [28]:
pd.DataFrame([data_series, data_seriesA])

          0    1    2    3    4    5    6    7    8    9
notas   7.5  8.0  6.2  9.3  5.8  4.7  8.9  7.1  6.5  9.8
notasA  7.5  8.0  6.2  9.3  5.8  4.7  8.9  7.1  6.5  9.8

In [8]:
pd.DataFrame({'notas': data_series})

   notas
0    7.5
1    8.0
2    6.2
3    9.3
4    5.8
5    4.7
6    8.9
7    7.1
8    6.5
9    9.8

In [9]:
from datetime import datetime

In [10]:
datetime.now()

datetime.datetime(2025, 11, 25, 23, 9, 37, 976977)